---
sudo: false

language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

stages:
  - analyze
  - test
  - release

jobs:
  fast_finish: true
  allow_failures:
    - php: 7.4snapshot
  include:
    - stage: analyze
      php: 7.3
      install:
        - phpenv config-rm xdebug.ini
        - composer install --prefer-dist
      script:
        - vendor/bin/phpunit
        - vendor/bin/php-cs-fixer --dry-run --stop-on-violation fix
        - composer validate

cache:
  directories:
    - $HOME/.composer
    - build/cache

install:
  - phpenv config-rm xdebug.ini || true
  - composer remove --no-update --dev friendsofphp/php-cs-fixer ergebnis/composer-normalize
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit

